### ISSUE TITLE
Camera stuttering appears when I remove the Operator collection and bring it back to its place

### ISSUE THREAD

**Issue by ProgrammingLife** [astrochili/defold-kinematic-walker#14]
Here are two videos of that behaviour. Here is the broken one:

https://github.com/astrochili/defold-kinematic-walker/assets/12764670/0e5aecc4-bd45-4fd0-a0eb-9653e6e44ddb

And the correct one. Simply it's just the original source without almost no changes. I just set the `smoothness` to 0.0005 for both cases to see the difference more clearly.

https://github.com/astrochili/defold-kinematic-walker/assets/12764670/a349629c-6145-4b12-b1bf-bc30dc25cb27

And here are the sources of those videos. The all difference as far as I see is in the order of collections in **player.collection** file. If I just playce the operator collection there higher that dummy one - then all works perfectly. Therefore when I removed operator.collection from the editor it just reorders the collection in **player.collection** and placed the operator collection to the end of that **player.collection** file.

[defold-kinematic-walker_broken.zip](https://github.com/astrochili/defold-kinematic-walker/files/12845883/defold-kinematic-walker_broken.zip)
[defold-kinematic-walker_correct.zip](https://github.com/astrochili/defold-kinematic-walker/files/12845884/defold-kinematic-walker_correct.zip)

**Comment by astrochili** [comment]
Thanks! Will try to find possible solutions as soon as possible.
