### ISSUE TITLE
Player is falling when resume pause

### ISSUE THREAD

**Issue by ufgo** [astrochili/defold-kinematic-walker#7]
https://user-images.githubusercontent.com/21050233/182414705-841feac4-37c2-4cf4-80f5-528f650ac8a4.mov

When pause 	
`msg.post(msg.url('player#walker'), hash 'pause', {is_paused = true})
`
then load level from proxy
unpause 
and player is fall :(

**Comment by astrochili** [comment]
Please, provide a minimal reproducing project based on the example in this repo 🙏

**Comment by ufgo** [comment]
> Please, provide a minimal reproducing project based on the example in this repo 🙏
[pause_bug.zip](https://github.com/astrochili/defold-kinematic-walker/files/9243881/pause_bug.zip)
