### ISSUE TITLE
Trigger collision response is broken

### ISSUE THREAD

**Issue by blisteredMind** [astrochili/defold-kinematic-walker#9]
In function handle_trigger_response the initial logic check for the sender url is trying to match to the variable self.current_collision_url which is not set anywhere else in the script, therefore making it always nil.

**Comment by astrochili** [comment]
Definitely, it should just be `self.collision` and not `self.current_collision_url`.

Thanks, I'm preparing a set of updates with use `fixed_update()` now and gonna include also this one.
